[package]
org = "ballerina"
name = "xmldata"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["xml", "json"]
repository = "https://github.com/ballerina-platform/module-ballerina-xmldata"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/xmldata-native-@project.version@.jar"
