[package]
org = "ballerina"
name = "xmldata"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["xml", "json"]
repository = "https://github.com/ballerina-platform/module-ballerina-xmldata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "xmldata-native"
version = "@toml.version@"
path = "../native/build/libs/xmldata-native-@project.version@.jar"
