[package]
org = "ballerina"
name = "xmldata"
version = "2.4.0"
authors = ["Ballerina"]
keywords = ["xml", "json"]
repository = "https://github.com/ballerina-platform/module-ballerina-xmldata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "xmldata-native"
version = "2.4.0"
path = "../native/build/libs/xmldata-native-2.4.0.jar"
