[package]
org = "ballerina"
name = "xmldata"
version = "2.2.2"
authors = ["Ballerina"]
keywords = ["xml", "json"]
repository = "https://github.com/ballerina-platform/module-ballerina-xmldata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/xmldata-native-2.2.2-SNAPSHOT.jar"
