[package]
org = "ballerina"
name = "xmldata"
version = "2.1.0"
authors = ["Ballerina"]
keywords = ["xml", "json"]
repository = "https://github.com/ballerina-platform/module-ballerina-xmldata"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/xmldata-native-2.1.0-SNAPSHOT.jar"
