[package]
org = "ballerina"
name = "xmldata"
version = "2.7.0"
authors = ["Ballerina"]
keywords = ["xml", "json"]
repository = "https://github.com/ballerina-platform/module-ballerina-xmldata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "xmldata-native"
version = "2.7.0"
path = "../native/build/libs/xmldata-native-2.7.0.jar"
