[package]
org = "ballerina"
name = "xmldata"
version = "2.0.1"
authors = ["Ballerina"]
keywords = ["xml", "json"]
repository = "https://github.com/ballerina-platform/module-ballerina-xmldata"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/xmldata-native-2.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/xmldata-test-utils-2.0.1-SNAPSHOT.jar"
scope = "testOnly"
