[plugin]
id = "xmldata-compiler-plugin"
class = "io.ballerina.stdlib.xmldata.compiler.XmldataCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/xmldata-compiler-plugin-2.7.1-SNAPSHOT.jar"
